### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by liukliukliuk** [notjosh/emoji-converti#1]
is there a noob friendly way to do that?

**Comment by notjosh** [comment]
How noob is noob in this case? Are you familiar with Homebrew and running terminal commands? If you can get that far, I can give you the commands!

**Comment by liukliukliuk** [comment]
not with homebrew, and I use Linux but I know how to use terminal tho

Il dom 13 feb 2022, 19:15 Joshua May ***@***.***> ha scritto:

**Comment by notjosh** [comment]
Since you use Linux, it gave me the idea to convert to script to work with Docker. So it for sure works on Linux now! As long as you have a copy of an Apple emoji font ("Apple Color Emoji.ttc"), then this repo should work ok.

So you have two options, depending what you're most comfortable with:

1. Run via Docker, if you have Docker installed (`./run-in-docker.sh /path/to/AppleFont.ttc`)
2. Install prerequisites, run manually (`sudo apt update; sudo apt --yes install fontforge fonttools python3-fonttools xmlstarlet; ./src/convert.sh /path/to/AppleFont.ttc ./assets/AppleColorEmoji.ttf`)

**Comment by liukliukliuk** [comment]
thank you so much! <3
